---

env:

  contexts:

  - name: "demo.testfire.net"

    urls:

    - "https://demo.testfire.net"

    includePaths:

    - "https://demo.testfire.net.*"

    excludePaths: []

    authentication:

      method: "form"

      parameters:

        loginPageUrl: "https://demo.testfire.net/doLogin"

        loginRequestUrl: "https://demo.testfire.net/doLogin"

        loginRequestBody: "uid={%username%}&passw={%password%}&btnSubmit=Login"

      verification:

        method: "response"

        loggedInRegex: "\\Q\" >MY ACCOUNT</a>\\E"

        pollFrequency: 60

        pollUnits: "requests"

        pollUrl: ""

        pollPostData: ""

    sessionManagement:

      method: "cookie"

      parameters: {}

    users:

    - name: "admin"

      username: "admin"

      password: "admin"

  parameters:

    failOnError: true

    failOnWarning: false

    progressToStdout: true

  vars: {}

jobs:

- parameters:

    user: "admin"

  requests:

  - url: "https://demo.testfire.net"

    name: ""

    method: "GET"

    data: ""

    responseCode: 200

  tests:

  - type: "stats"

    statistic: "stats.auth.state.loggedin"

    site: "https://demo.testfire.net"

    operator: ">="

    value: 1

    onFail: "error"

  name: "requestor"

  type: "requestor"
